### ISSUE TITLE
Chat needs to be channel specific

### ISSUE THREAD

**Issue by Nitishdevrani** [aws-samples/amazon-ivs-simple-chat-web-demo#15]
we are using Ivs for streaming in which we integrated ivs player with simple chat using this tutorial {"https://github.com/aws-samples/amazon-ivs-simple-chat-web-demo/blob/master/serverless/README.md"}.
Right now, we are getting the same chat messages for different channels stream.

![Screenshot from 2022-02-02 15-31-47](https://user-images.githubusercontent.com/60418980/152983691-2a326c2c-99fd-4817-9416-39af52d3837e.png)
![Screenshot from 2022-02-02 15-31-57](https://user-images.githubusercontent.com/60418980/152983705-fed098a0-05d3-49c8-abea-7a56d1d46af1.png)

Our requirement is that the chat should be channel-specific.

Just like different channel-arn can live different streams, we need different WebSocket to be auto-created with channel creation so that we can use different WebSocket for different streams.

**Comment by slee-aws** [comment]
@Nitishdevrani Unfortunately this demo does not currently support multiple chat rooms. However, we are considering official support for multiple rooms in a future update. 

If you are comfortable working with AWS Lambda and javascript, you could consider an approach similar to the one described in this post: [link](https://stackoverflow.com/questions/63731159/how-to-implement-multiple-chat-rooms-with-aws-api-gateway-websockets).

Keep in mind that this demo isn't designed to run at high volumes or scale, so if your use-case involves a significant number of users chatting concurrently, this may not be the ideal solution.

Since this isn't something we are able to address right now, I'll close this issue thread. Please feel free to re-open or create a new github issue if you have any other needs.
